from fpdf import FPDF
from io import BytesIO

def generate_pdf(title: str, ingredients: list, instructions: str):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, txt=title, ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 10, "Ingredients:\n" + "\n".join(ingredients))
    pdf.ln(5)
    pdf.multi_cell(0, 10, "Instructions:\n" + instructions)
    pdf.ln(5)
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, "Generated by DRG 4.0", ln=True, align='R')

    buffer = BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    return buffer
